<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>me.bananplayss</groupId>
        <artifactId>castlewars-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>castlewars-core</artifactId>
    <version>${project.parent.version}</version>
    <packaging>jar</packaging>

    <name>castlewars-core</name>

    <properties>
        <!--        <maven.compiler.source>17</maven.compiler.source>-->
        <!--        <maven.compiler.target>17</maven.compiler.target>-->
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <build>
        <defaultGoal>clean package</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>
                <configuration>
                    <outputDirectory>C:\Users\Balu\Desktop\Servers\1.18.2\plugins</outputDirectory>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
<!--                    <minimizeJar>false</minimizeJar>-->
<!--                    <createDependencyReducedPom>false</createDependencyReducedPom>-->
                    <relocations>
                        <relocation>
                            <pattern>com.cryptomorin.xseries</pattern>
                            <!-- Be sure to change the package below -->
                            <shadedPattern>me.bananplayss.xseries</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>fr.mrmicky.fastboard</pattern>
                            <!-- Replace 'com.yourpackage' with the package of your plugin -->
                            <shadedPattern>me.bananplayss.fastboard</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>com.jeff_media.armorequipevent</pattern>
                            <shadedPattern>me.bananplayss.castlewars.armorequipevent</shadedPattern>
                        </relocation>
<!--                        <relocation>-->
<!--                            <pattern>com.github.retrooper</pattern>-->
<!--                            <shadedPattern>me.bananplayss.castlewars.libs.packetevents</shadedPattern>-->
<!--                        </relocation>-->
<!--                        <relocation>-->
<!--                            <pattern>io.github.retrooper</pattern>-->
<!--                            <shadedPattern>me.bananplayss.castlewars.libs.packetevents</shadedPattern>-->
<!--                        </relocation>-->
<!--                        <relocation>-->
<!--                            <pattern>net.kyori</pattern>-->
<!--                            <shadedPattern>me.bananplayss.castlewars.libs.kyori</shadedPattern>-->
<!--                        </relocation>-->
<!--                        <relocation>-->
<!--                            <pattern>com.google.gson</pattern>-->
<!--                            <shadedPattern>me.bananplayss.castlewars.libs.gson</shadedPattern>-->
<!--                        </relocation>-->
                    </relocations>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>com/cryptomorin/xseries/XBiome*</exclude>
                                <exclude>com/cryptomorin/xseries/NMSExtras*</exclude>
                                <exclude>com/cryptomorin/xseries/NoteBlockMusic*</exclude>
                                <exclude>com/cryptomorin/xseries/SkullCacheListener*</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.46</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.helpch.at/releases/</url>
        </repository>
        <repository>
            <id>enginehub</id>
            <url>https://maven.enginehub.org/repo/</url>
        </repository>

        <repository>
            <id>codemc-releases</id>
            <url>https://repo.codemc.io/repository/maven-releases/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <!--    <dependencyManagement>-->
    <!--        <dependencies>-->
    <!--            <dependency>-->
    <!--                <groupId>com.intellectualsites.bom</groupId>-->
    <!--                <artifactId>bom-newest</artifactId> &lt;!&ndash;  Ref: https://github.com/IntellectualSites/bom &ndash;&gt;-->
    <!--                <version>1.56</version>-->
    <!--                <scope>import</scope>-->
    <!--                <type>pom</type>-->
    <!--            </dependency>-->
    <!--        </dependencies>-->
    <!--    </dependencyManagement>-->

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.18.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>me.bananplayss</groupId>
            <artifactId>castlewars-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.46</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.12.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>7.1.0</version>
        </dependency>
        <!--         Source: https://mvnrepository.com/artifact/net.kyori/adventure-text-minimessage -->
        <!--        <dependency>-->
        <!--            <groupId>net.kyori</groupId>-->
        <!--            <artifactId>adventure-text-minimessage</artifactId>-->
        <!--            <version>5.1.1</version>-->
        <!--            <scope>compile</scope>-->
        <!--        </dependency>-->
        <dependency>
            <groupId>com.github.cryptomorin</groupId>
            <artifactId>XSeries</artifactId>
            <version>13.7.0</version>
        </dependency>

        <dependency>
            <groupId>com.fastasyncworldedit</groupId>
            <artifactId>FastAsyncWorldEdit-Core</artifactId>
            <version>2.9.2</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.jeff-media</groupId>
            <artifactId>armor-equip-event</artifactId>
            <version>1.0.3</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.fastasyncworldedit</groupId>
            <artifactId>FastAsyncWorldEdit-Bukkit</artifactId>
            <version>2.9.2</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>fr.mrmicky</groupId>
            <artifactId>fastboard</artifactId>
            <version>2.2.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.retrooper</groupId>
            <artifactId>packetevents-spigot</artifactId>
            <version>2.13.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.github.NEZNAMY</groupId>
            <artifactId>TAB-API</artifactId>
            <version>6.0.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>